#pragma once

#include "assetc/hash.hpp" // HashAssetRef (SDK)
#include "assetc/runtime_anim.hpp"
#include "assetc/runtime_mesh.hpp"

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

namespace obj
{
struct OBJ;
}

namespace gltf
{
struct GLTF;
}

namespace assetc
{

// Tunables for the reduced-LOD levels generated per submesh (meshopt_simplify).
// See docs/hmesh.md and assetc.yml's `mesh.lod` block, which this mirrors.
struct LodParams
{
    std::vector<float> ratios = {0.5f, 0.25f}; // target index-count fraction per level, from LOD0
    float              targetError    = 0.05f; // meshopt_simplify target_error (0..1), first attempt
    float              errorStep      = 0.05f; // relax target_error by this much per retry on stall
    uint32_t           maxAttempts    = 3;     // retries at relaxed error before falling back
    bool               sloppyFallback = true;  // meshopt_simplifySloppy if still stalled after retries
};

struct CompiledMesh
{
    Mesh                  mesh;         // GpuVertex array + indices + meshlets (all submeshes concatenated)
    MeshBounds            bounds;       // mesh-wide AABB + sphere
    std::vector<SubMesh>  submeshes;    // one per source primitive; index/meshlet ranges + material slot
    std::vector<uint64_t> materialRefs; // FNV1a64 hashes, compact: only materials referenced by a submesh
    std::vector<uint32_t> materialSourceIndex; // dense slot -> source material index (parallel to materialRefs)
    std::vector<GpuJoint> skeleton;     // SKEL: empty unless the source is skinned
    std::vector<AnimClip> animations;   // written to a companion .hanim; empty if none
};

// Build a runtime-ready mesh from a parsed OBJ.
//
// `sourceRef` is the **source-file** runtime key in canonical form (forward
// slashes, lowercase, no leading "runtime/", no extension). Example: a source
// asset at `assets/models/chair.obj` becomes `sourceRef = "models/chair"`.
//
// The same `sourceRef` is shared across all meshes extracted from one source
// file (this matters mainly for glTF where one .glb yields many .hmesh files).
// Materials live in this same namespace, so engine-side dedupe works across
// meshes from the same source.
//
// materialRefs is compact: it contains only the materials actually referenced by
// a submesh, in first-use order. SubMesh::materialSlot indexes into it (or is
// kNoMaterial). Leaf-name disambiguation still uses the full source material set,
// so refs stay stable across meshes from the same source.
//
// On failure, the returned CompiledMesh has empty vectors.
CompiledMesh BuildFromObj(const obj::OBJ &src, std::string_view sourceRef,
                          const LodParams &lod = {});

// Build a runtime-ready mesh from a parsed glTF/GLB.
//
// Exports every primitive of mesh[0] as a SubMesh (one material each). Multi-mesh
// sources still export only mesh[0] (the remaining meshes belong to a scene asset);
// a warning is logged when more meshes are present.
//
// Uses source TANGENT attribute if present; otherwise runs MikkTSpace if UVs
// are present; otherwise emits zero tangents and warns. Synthesizes face normals
// if NORMAL is absent.
//
// glTF UVs are top-left-origin (matches Vulkan), so no V flip applied.
//
// `mergeNodes` (default true) bakes each node's world transform into its vertices,
// combining the scene graph into one world-space mesh. When false, geometry is
// kept in its source-local space (node transforms are not baked); skinned meshes
// are never baked regardless.
CompiledMesh BuildFromGltf(const gltf::GLTF &src, std::string_view sourceRef,
                           bool mergeNodes = true, const LodParams &lod = {});

// HashAssetRef now lives in the SDK (assetc/hash.hpp, included above) so the
// engine and the encoder compute refs the same way.

// Derive the leaf segment of a material's runtime ref, format-agnostic.
//   - If `name` is non-empty AND its lowercased form is unique within
//     `allNames` (case-insensitive), returns the lowercased name.
//   - Otherwise returns "material_<index>" as a stable index-based fallback.
//
// glTF reality: material names are commonly empty, duplicated, or junk
// auto-generated by DCC tools. The fallback keeps every material addressable
// by a unique, stable identifier regardless of how the source was authored.
std::string MaterialLeaf(std::string_view name, size_t index,
                         std::span<const std::string_view> allNames);

} // namespace assetc
