#pragma once

#include "runtime_mesh.hpp"

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

namespace obj
{
struct OBJ;
}

namespace gltf
{
struct GLTF;
}

namespace assetc
{

struct CompiledMesh
{
    Mesh                  mesh;         // GpuVertex array + indices + meshlets
    MeshBounds            bounds;       // mesh-wide AABB + sphere
    std::vector<uint64_t> materialRefs; // FNV1a64 hashes, one per source material, in source-index order
};

// Build a runtime-ready mesh from a parsed OBJ.
//
// `sourceRef` is the **source-file** runtime key in canonical form (forward
// slashes, lowercase, no leading "runtime/", no extension). Example: a source
// asset at `assets/models/chair.obj` becomes `sourceRef = "models/chair"`.
//
// The same `sourceRef` is shared across all meshes extracted from one source
// file (this matters mainly for glTF where one .glb yields many .hmesh files).
// Materials live in this same namespace, so engine-side dedupe works across
// meshes from the same source.
//
// materialRefs is emitted in source-index order (one entry per material in
// `src.materials`), so SUBM chunks (v2) can reference materials by index
// directly without any remap.
//
// On failure, the returned CompiledMesh has empty vectors.
CompiledMesh BuildFromObj(const obj::OBJ &src, std::string_view sourceRef);

// Build a runtime-ready mesh from a parsed glTF/GLB.
//
// v1 limitation: emits only the first primitive of the first mesh in the source.
// Multi-mesh / multi-primitive support requires a SUBM chunk (v2). All materials
// from the source are still hashed in source-index order so engine-side material
// dedupe works correctly even though only one primitive's geometry is exported.
//
// Uses source TANGENT attribute if present; otherwise runs MikkTSpace if UVs
// are present; otherwise emits zero tangents and warns. Synthesizes face normals
// if NORMAL is absent.
//
// glTF UVs are top-left-origin (matches Vulkan), so no V flip applied.
CompiledMesh BuildFromGltf(const gltf::GLTF &src, std::string_view sourceRef);

// FNV1a64 hash of a runtime-relative asset reference. Caller-side normalization
// (lowercase, /-separated, no extension, no leading "runtime/" prefix) is the
// authoritative format; this function additionally lowercases ASCII A-Z for
// belt-and-braces consistency.
uint64_t HashAssetRef(std::string_view runtimeRefNoExt) noexcept;

// Derive the leaf segment of a material's runtime ref, format-agnostic.
//   - If `name` is non-empty AND its lowercased form is unique within
//     `allNames` (case-insensitive), returns the lowercased name.
//   - Otherwise returns "material_<index>" as a stable index-based fallback.
//
// glTF reality: material names are commonly empty, duplicated, or junk
// auto-generated by DCC tools. The fallback keeps every material addressable
// by a unique, stable identifier regardless of how the source was authored.
std::string MaterialLeaf(std::string_view name, size_t index,
                         std::span<const std::string_view> allNames);

} // namespace assetc
