# ktx
set(KTX_INSTALL_DIR ${CMAKE_BINARY_DIR}/ktx-install)
ExternalProject_Add(
    ktx_external
    GIT_REPOSITORY    https://github.com/KhronosGroup/KTX-Software.git
    GIT_TAG           v4.4.2
    GIT_SHALLOW       TRUE

    PREFIX            ${CMAKE_BINARY_DIR}/ktx
    INSTALL_DIR       ${KTX_INSTALL_DIR}

    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DKTX_FEATURE_TESTS=OFF
        -DKTX_FEATURE_TOOLS=OFF
        -DKTX_FEATURE_STATIC_LIBRARY=ON
        -DKTX_FEATURE_VK_UPLOAD=ON
        -DKTX_FEATURE_GL_UPLOAD=OFF
        -DKTX_FEATURE_KTX1=OFF
        -DKTX_FEATURE_KTX2=ON
        -DBASISU_SUPPORT_SSE=ON

    BUILD_BYPRODUCTS
        <INSTALL_DIR>/lib/${CMAKE_STATIC_LIBRARY_PREFIX}ktx${CMAKE_STATIC_LIBRARY_SUFFIX}

    UPDATE_DISCONNECTED 1
)

